config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  devise_for :users, skip: :registrations, controllers: {
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
  }

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root 'welcome#index', as: 'home'
  
  get 'about' => 'welcome#about', as: 'about'
  get '404' => 'welcome#not_found', as: 'not_found'
  
  get 'articles' => 'articles#index', as: 'articles'
  get 'articles/:id' => 'articles#show', as: 'article'

  get 'events/:id' => 'events#show', as: 'event'
  get 'events' => 'events#index', as: 'events'

  get 'teachers/:id' => 'teacher#show', as: 'teacher'
  get 'teachers' => 'teacher#index', as: 'teachers'
  
  get 'oportunities/:id' => 'oportunities#show', as: 'oportunity'
  get 'oportunities' => 'oportunities#index', as: 'oportunities'  
  get 'disciplines' => 'discipline#index', as: 'disciplines'
  
  namespace :dashboard do
    root 'articles#index', as: 'root'
    resources :articles, except: [:show]
    resources :events, except: [:show]
    resources :disciplines, except: [:show]
    resources :oportunities, except: [:show]
    resources :users, except: [:show]
    resources :discipline_classes, except: [:show]
    resources :materials, except: [:show]

    get 'profile' => 'profile#index', as: 'profile'
    post 'profile' => 'profile#update', as: 'profile_update'
  end

  scope 'portalC3' do
    namespace :api do
      get 'posts' => 'article#index'
      get 'posts/:id' => 'article#show'

      get 'eventos' => 'event#index'
      get 'eventos/:id' => 'event#show'

      get 'disciplinas' => 'discipline#index'

      get 'oportunidades' => 'oportunity#index'
      get 'oportunidades/:id' => 'oportunity#show'

      get 'professores' => 'teacher#index'
      get 'professores/:id' => 'teacher#show'
    end
  end

end

app/models/user.rb
# Classe de usuário
class User < ActiveRecord::Base
  # Funcoes do devise
  # - database_authenticatable: Indica que essa classe é autenticável
  # - registerable: Indica que essa classe é registrável
  # - recoverable: Indica que essa classe possui recuperação de senha
  # - rememberable: Faz com que a autenticação se mantenha em cache
  # - trackable: Indica que essa classe é rastreável (Quantidade de logins, ultimo login, etc)
  # - validatable: Indica que essa classe é validável pelo devise (Tamanho da senha, campos obrigatórios, confirmação da senha)
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Enum de nível de usuário
  # são utilizados para saber que tipo de usuário
  # pode ou não criar e/ou remover outros usuários
  enum role: [:admin, :user]

  has_many :articles
  has_many :events
  has_many :events
  has_many :discipline_classes
  belongs_to :user_profile
  has_and_belongs_to_many :disciplines

  # Para facilitar o uso futuro, foi abreviado para profile apenas
  alias :profile :user_profile
  alias :classes :discipline_classes

  # Define o tipo de imagem que a notícia pode ter
  has_attached_file :avatar, :styles => {
      :medium => ["300x300>", :jpg],
      :thumb => ["100x100>", :jpg]
  }

  # Valida o tipo de arquivo a imagem da notícia pode ser
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.reset_password(id, password)
    user = find id
    user.password = password
    user.save
  end

end

app/controllers/api/teacher_controller.rb
class Api::TeacherController < ApplicationController

    def index
        @teachers = User.joins(:user_profile).
            eager_load(:disciplines).
            where("user_profiles.is_teacher = true").
            paginate(:page => params[:page], :per_page => 30)
        @json = []
        for teacher in @teachers
            @post = to_json teacher
            @json << @post
        end
        render :json => @json
    end
    
    def show
        @teacher = User.where(id: params[:id]).
            joins(:user_profile).
            eager_load(:disciplines).
            first
        
        render :json => to_json(@teacher)
    end
    
    private
    def to_json(teacher)
        teacher.to_json
        disciplines = []
        files = []
        if not teacher.discipline_ids.nil?
            teacher.disciplines.each do |discipline|
                disciplines << {
                    disciplinaNome: discipline.name,
                    disciplinaCodigo: discipline.code
                }
            end
        end
        if not teacher.discipline_class_ids.nil?
            teacher.discipline_classes.each do |discipline|
                files << {
                    turmaNome: discipline.name,
                    disciplinaCodigo: discipline.discipline.code,
                    arquivos: discipline.make_json(request)
                }
            end
        end
        {
            professorId: teacher.id,
            professorNome: teacher.name,
            professorLattes: teacher.profile.lattes,
            professorTitulacao: teacher.profile.degree,
            professorCargo: (teacher.profile.role.nil? ? 'Professor' : teacher.profile.role),
            professorImagemUrl: "#{request.protocol}#{request.host}#{teacher.avatar.url}",
            professorInteresses: teacher.profile.interests,
            professorEmail: teacher.email,
            professorTelefone: teacher.profile.phone,
            professorDisciplinas: disciplines,
            professorDisciplinasArquivos: files
        }
    end

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  def show
    begin
      @teacher = User.where(id: params[:id]).
          joins(:user_profile).
          eager_load(:disciplines).
          first
    rescue
      redirect_to not_found_path()
    end
  end

  def index
    @teachers = User.joins(:user_profile).
        eager_load(:disciplines).
        where("user_profiles.is_teacher = true").
        paginate(:page => params[:page], :per_page => 30)
  end
end

app/views/teacher/index.html.erb
<div class="col-lg-8 col-md-8">
    <div class="col-padded">
        <div class="row gutter">
            <div class="col-lg-12 col-md-12">
                <h1 class="page-title">Corpo Docente</h1>
            </div>
        </div>
        <div class="row gutter">
            <div class="col-lg-12 col-md-12">
                <table class="table table-striped table-courses">
                    <thead>
                        <tr>
                            <th>Nome</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @teachers.sort_by(&:name).each do |teacher| %>
                            <tr>
                                <td>
                                    <a href="<%= teacher_path(teacher) %>" title="<%= teacher.name %>">
                                        <%= teacher.name %>
                                    </a>
                                </td>
                                <td>
                                    <a href="<%= teacher_path(teacher) %>" title="<%= teacher.name %>">+ mais informações</a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/teacher/show.html.erb
<div class="col-lg-8 col-md-8">
  <div class="col-padded">
    <div class="row gutter">
      <div class="col-lg-12 col-md-12">
        <div class="course-title-meta clearfix">
          <h1 class="page-title" style="text-transform:uppercase"><%= @teacher.name %></h1>
          <dl class="dl-horizontal course-meta">
            <img src="<%=@teacher.avatar.url %>" alt="<%= @teacher.name %>" width="150" height="150" />
            <dt>Cargo: </dt>
            <dd>
              <%= @teacher.profile.role.nil? ? 'Professor' : @teacher.profile.role %>
            </dd>
            <dt>Titulação:</dt>
            <dd>
              <%= @teacher.profile.degree %>
            </dd>
            <dt>Currículo Lattes:</dt>
            <dd>
              <a href="<%= @teacher.profile.lattes %>" target="_blank">Clique Aqui</a>
            </dd>

          </dl>
        </div>
        <div class="news-body clearfix">
          <dt>Areas de Interesse:</dt>
          <p align="justify">
            <%= @teacher.profile.interests %>
          </p>
          <dt><font size=2.8>E-mail:</font></dt>
          <dd>
            <%= @teacher.email %>
            </font>
          </dd>
          <dt><font size=2.8>Fone:</dt>
          <dd>
            <%= @teacher.profile.phone %>
            </font>
          </dd>
          <% unless @teacher.profile.link.empty? %>
              <dt><font size=2.8>Página Pessoal:</font></dt>
              <dd><a href="<%= @teacher.profile.link %>" target="_blank"><%= @teacher.profile.link %></a></font>
              </dd>
          <% end %>
          <% if not @teacher.discipline_ids.nil? and @teacher.discipline_ids.size > 0 %>
              <h6>Material de aula:</h6>
              <% @teacher.disciplines.each do |discipline| %>
              <br/>
              <p onclick="$('.classes').hide(); $('.classes[data-discipline-id=<%=discipline.id%>]').show();"><font size='2.5'><%= discipline.code %> - <%= discipline.name %></font></p>
              <ul class="list-unstyled classes list-downloads" data-discipline-id="<%= discipline.id %>" style="display: none;">
                <li>
                  <% @teacher.classes.where(discipline_id: discipline.id).each do |classe| %>
                    <p onclick="$('.class').hide(); $('.class[data-class-id=<%=classe.id%>]').show();"><%= classe.name %></p>
                    <ul class="list-unstyled class list-downloads" data-class-id="<%= classe.id %>" style="display: none;">
                      <% classe.attachments.each do |attachment| %>
                        <li>
                          <i class="fa fa-cloud-download"></i>
                          <a href="<%= attachment.url%>" target="_blank" title="<%= attachment.original_filename %>" class="download-link">
                            <span class="dwnld-title"></span>
                            <span class="help-block"><%= attachment.original_filename %></span>
                          </a>
                        </li>
                      <% end %>
                    </ul>
                  <% end %>
                </li>
              </ul>
              <% end %>
          <% end %>
          <hr/>
        </div>
      </div>
    </div>
  </div>
</div>