config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  devise_for :users, skip: :registrations, controllers: {
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
  }

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root 'welcome#index', as: 'home'
  
  get 'about' => 'welcome#about', as: 'about'
  get '404' => 'welcome#not_found', as: 'not_found'
  
  get 'articles' => 'articles#index', as: 'articles'
  get 'articles/:id' => 'articles#show', as: 'article'

  get 'events/:id' => 'events#show', as: 'event'
  get 'events' => 'events#index', as: 'events'

  get 'teachers/:id' => 'teacher#show', as: 'teacher'
  get 'teachers' => 'teacher#index', as: 'teachers'
  
  get 'oportunities/:id' => 'oportunities#show', as: 'oportunity'
  get 'oportunities' => 'oportunities#index', as: 'oportunities'  
  get 'disciplines' => 'discipline#index', as: 'disciplines'
  
  namespace :dashboard do
    root 'articles#index', as: 'root'
    resources :articles, except: [:show]
    resources :events, except: [:show]
    resources :disciplines, except: [:show]
    resources :oportunities, except: [:show]
    resources :users, except: [:show]
    resources :discipline_classes, except: [:show]
    resources :materials, except: [:show]

    get 'profile' => 'profile#index', as: 'profile'
    post 'profile' => 'profile#update', as: 'profile_update'
  end

  scope 'portalC3' do
    namespace :api do
      get 'posts' => 'article#index'
      get 'posts/:id' => 'article#show'

      get 'eventos' => 'event#index'
      get 'eventos/:id' => 'event#show'

      get 'disciplinas' => 'discipline#index'

      get 'oportunidades' => 'oportunity#index'
      get 'oportunidades/:id' => 'oportunity#show'

      get 'professores' => 'teacher#index'
      get 'professores/:id' => 'teacher#show'
    end
  end

end

app/controllers/welcome_controller.rb
# Esse controller é utilizado apenas para
# páginas simples na página que o usuário não
# autenticado pode ver
class WelcomeController < ApplicationController

  # A página principal '/' do portal
  # Deve:
  # - Mostrar os 5 últimos posts
  # - Mostrar os 5 últimos eventos
  def index
    @latest_articles = Article.last(5).reverse
    @latest_events = Event.last(5).reverse
    
  end
  
  # Link para página de "Sobre"
  def about
  
  end
  
  # Link para página de "404 not found"
  def not_found
  
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
    <div class="col-lg-8 col-md-8">


        <div class="col-padded">


            <div class="gutter">


                <div class="col-lg-12 col-md-12">



                    <h1 class="page-title">Sobre o curso</h1>

                    <div class="news-body">

                        <p class="call-out">
                            <br><b>Modalidade:</b> Bacharelado</br>
                            <br><b>Reconhecimento:</b> Portaria MEC nº 602, de 10.08.1986. Publicação no DOU, 20.08.1986</br>
                            <br><b>Turnos Oferecidos:</b> Tarde e Noite</br>
                            <br><b>Carga horária:</b> 3.200 horas</br>
                            <br><b>Duração do curso:</b> 8 períodos, mínimo; 16 períodos, máximo</br>
                            <br><b>Créditos:</b> 206 obrigatórios e eletivos</br>
                            <br><b>Coordenação:</b> Prof. MSc. Márcio Augusto Silva Bueno (masb@unicap.br)</br>
                            <br><b>Secretaria do curso:</b> Bloco D – Térreo – Fone: (81) 2119-4240</br>
                        </p>



                    </div>

                    <div class="news-body">
                        <h1 class="page-title">Objetivo</h1>
                        <p class="call-out">
                            <p align="justify"> O Curso de Ciência da Computação da UNICAP tem como objetivo formar profissionais capazes de contribuir, eticamente, com o desenvolvimento científico e tecnológico da computação, a fim de atender às necessidades das organizações
                                e da sociedade</p>
                        </p>



                    </div>

                    <div class="news-body">
                        <h1 class="page-title">Perfil Profissional</h1>
                        <p class="call-out">
                            <p align="justify"> Os bacharéis em Ciência da Computação estão capacitados a atuar nas diversas áreas da Computação, embasados em um aprendizado que possibilite o conhecimento científico e a prática profissional tecnologicamente atualizada e
                                inserida no contexto social. Esses profissionais estão aptos a identificar e solucionar problemas de informação do mundo contemporâneo, através da modelagem adequada desses problemas e da utilização de recursos computacionais
                                e humanos nas suas soluções, pesquisando, analisando e dominando o processo da informática.</p>
                        </p>



                    </div>
                    <div class="news-body">
                        <h1 class="page-title">Mercado de Trabalho</h1>
                        <p class="call-out">
                            <p align="justify"> Ao Bacharel em Ciência da Computação compete atuar em empresas da área de Computação de uma forma geral ou exercer sua capacidade empreendedora, criando sua própria empresa, voltada para o desenvolvimento de ferramentas para
                                ambientes computacionais e de novas tecnologias para áreas comerciais, técnicas e de aplicações gerais. Áreas de atuação: desenvolvimento de sistemas de informação, desempenhando os papéis de analista de sistemas, programador
                                de sistemas, gerente de desenvolvimento de sistemas, gerente de projetos de sistemas; infra-estrutura de tecnologia da informação, desempenhando funções tais como analista de suporte, administrador de banco de dados, gerente
                                de redes de computadores; gestão de sistemas de informação como gerente de sistemas de informação, consultor/auditor em gestão de sistemas de informação. O Bacharel em Ciências da Computação poderá, também, seguir a carreira
                                acadêmica, como docente ou pesquisador, ingressando em cursos de pós-graduação: especialização, mestrado e doutorado.</p>
                        </p>



                    </div>

                    <div class="news-body">
                        <h1 class="page-title">Atividades Complementares</h1>
                        <p class="call-out">
                            <p align="justify"> As Atividades Complementares são componentes curriculares de caráter científico, cultural e acadêmico cujo foco principal é o estímulo à prática de estudos independentes, transversais, opcionais e interdisciplinares, de forma
                                a promover, em articulação com as demais atividades acadêmicas, o desenvolvimento intelectual do estudante, seu preparo para o exercício da cidadania e sua qualificação para o trabalho. Quando são efetivadas de acordo com
                                as diretrizes da UNICAP, aprovadas pela Resolução CONSEPE/UNICAP nº 009/2005 de 06.05.2005, e promovem a aquisição de conhecimento e o desenvolvimento de competências e habilidades, verificados por meio de avaliação, serão
                                validadas academicamente pela UNICAP, mesmo se realizadas em situações de aprendizagem fora da Universidade, desde que vinculadas ao mundo do trabalho e à prática social.</p>
                        </p>



                    </div>

                    <div class="news-body">
                        <h1 class="page-title">Estágio Supervisionado</h1>
                        <p class="call-out">
                            <p align="justify"> Para a realização do Estágio os estudantes contam, além do mercado de trabalho, com o Laboratório de Pesquisa e Desenvolvimento (P&D) da Itautec, uma vez que a UNICAP, através do Departamento de Estatística e Informática, é
                                credenciada junto ao Ministério da Ciência e Tecnologia – MCT – através do Comitê da Área de Tecnologia da Informação – CATI.</p>
                        </p>



                    </div>

                    <div class="news-body">
                        <h1 class="page-title">Programas de Extensão</h1>
                        <p class="call-out">
                            <p align="justify">A extensão é entendida como prática acadêmica que aproxima a Universidade, nas suas atividades de ensino e pesquisa, às demandas da sociedade na qual ela está inserida, possibilitando, assim, a formação do profissional cidadão
                                e caracterizando o ambiente universitário como espaço privilegiado de produção do conhecimento significativo para superação das desigualdades sociais existentes.
                                <br>Dentre os programas de Extensão desenvolvidos, destacam-se:</br>
                                <li>Cursos, Conferências, Seminários</li>
                                <li>Atividades Artístico-Culturais</li>
                                <li>Atividades Desportivas</li>
                                <li>Assistência à Saúde</li>
                                <li>Assistência Espiritual e Religiosa</li>
                                <li>Assistência Estudantil</li>
                                <li>Assistência Social</li>
                                <li>Assistência Jurídica Gratuita</li>
                                <li>Assistência Psicológica e Fonoaudiológica</li>
                                <li>Apoio aos Movimentos Populares</li>
                                <li>Unicap para a 3ª Idade</li>
                                <li>Projeto Horizonte</li>
                            </p>
                        </p>

                    </div>
                    <div class="news-body">
                        <h1 class="page-title">Iniciação Científica</h1>
                        <p class="call-out">
                            <p align="justify"> O Programa Institucional de Base de Iniciação Científica – PIBIC/UNICAP foi implantado em 1998. Desde então, têm-se realizado as Jornada de Iniciação Científica e a Mostra de Pesquisa, Pós-graduação e Extensão, mobilizando
                                as comunidades interna e externa. A partir de 2003, tais eventos foram reunidos e fazem parte da Semana de Integração Universidade-Sociedade. O PIBIC/UNICAP conta com 330 bolsas da própria instituição, nos moldes do Conselho
                                Nacional de Desenvolvimento Científico e Tecnológico (CNPq), 30 bolsas do PIBIC/CNPq e 12 bolsas de Iniciação Científica da Fundação de Amparo à Ciência e à Tecnologia do Estado de Pernambuco (FACEPE) por demanda espontânea.
                            </p>
                        </p>
                    </div>
                    <div class="news-body">
                        <h1 class="page-title">Intercâmbio Estudantil</h1>
                        <p class="call-out">
                            <p align="justify">O Programa de Intercâmbio Estudantil oferecido pela UNICAP visa a propiciar aos alunos uma experiência acadêmica, durante um ou dois semestres, numa IES nacional ou internacional, através de convênios de cooperação mútua educacional.
                                Esse Programa tem sua origem nas diretrizes da AUSJAL – Associação de Universidades confiadas à Companhia de Jesus na América Latina, que propõe a integração dos estudantes de IES jesuítas latino-americanas, como modalidade
                                complementar de sua formação. Por outro lado, a UNICAP recebe estudantes estrangeiros das IES conveniadas que desejem realizar estudos de graduação por um ou dois semestres.</p>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/welcome/index.html.erb
<div class="col-lg-4 col-md-4">
    <div class="col-padded col-shaded">
        <% if not @latest_events.nil? and not @latest_events.empty? %>
        <ul class="list-unstyled clear-margins">
            <li class="widget-container widget_up_events">
                <h1 class="title-widget">Próximos Eventos</h1>
                <ul class="list-unstyled">
                    <% @latest_events.each do |event| %>
                    <li class="up-event-wrap">
                        <h1 class="title-median"><%= link_to event.title, event_path(event) %></h1>
                        <div class="up-event-meta clearfix">
                            <div class="up-event-date">
                                <%= event.date.strftime("%d/%m/%Y")%>
                            </div>
                            <div class="up-event-time">
                                <%= event.date.strftime("%H:%M")%>
                            </div>
                        </div>
                        <p>
                            <%= sanitize(event.description[0..30]) %>
                            <p><%= link_to 'Mais', event_path(event), class: 'moretag' %></p>
                        </p>
                    </li>
                    <% end %>
                </ul>
            </li>
        </ul>
        <% end %>
    </div>
</div>
<div class="col-lg-4 col-md-4">
    <% if not @latest_articles.nil? and not @latest_articles.empty? %>
    <div class="col-padded">
        <ul class="list-unstyled clear-margins">
            <li class="widget-container widget_recent_news">
                <h1 class="title-widget">Últimas Notícias</h1>
                <ul class="list-unstyled">
                    <% @latest_articles.each do |article| %>
                    <li class="recent-news-wrap">
                        <h1 class="title-median"><%= link_to article.title, article_path(article)%></h1>
                        <div class="recent-news-meta">
                            <div class="recent-news-date">
                                <%= article.updated_at.strftime("%d/%m/%Y")%>
                            </div>
                        </div>
                        <div class="recent-news-content clearfix">
                            <figure class="recent-news-thumb">
                                <a href="<%= article_path(article)%>" title="<%= article.title%>">
                                    <%= image_tag article.image.url, class: 'attachment-thumbnail wp-post-image' %>
                                </a>
                            </figure>
                            <div class="recent-news-text">
                                <p>
                                    <%= sanitize(article.description[0..20])%>
                                </p>
                            </div>
                        </div>
                    </li>
                    <% end %>
                </ul>
            </li>
        </ul>
    </div>
    <% end %>
</div>

app/views/welcome/not_found.erb
<div class="col-lg-8 col-md-8">
    <div class="col-padded">
        <h1 class="page-title text-center">404 Error</h1>
        <div class="news-body">
            <div class="row">
                <div class="col-lg-12">
                    <figure class="thumb-404">
                        <img src="/assets/img/404_error_image.png" alt="Error Image" class="img-responsive aligncenter" />
                    </figure>
                </div>
                <div class="col-lg-12">
                    <h6 class="text-center">Ooops!</h6>
                    <p class="text-center">
                        What an embarrassing situation, requested page can not be found or it doesn't exist.<br />
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>