config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  devise_for :users, skip: :registrations, controllers: {
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
  }

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root 'welcome#index', as: 'home'
  
  get 'about' => 'welcome#about', as: 'about'
  get '404' => 'welcome#not_found', as: 'not_found'
  
  get 'articles' => 'articles#index', as: 'articles'
  get 'articles/:id' => 'articles#show', as: 'article'

  get 'events/:id' => 'events#show', as: 'event'
  get 'events' => 'events#index', as: 'events'

  get 'teachers/:id' => 'teacher#show', as: 'teacher'
  get 'teachers' => 'teacher#index', as: 'teachers'
  
  get 'oportunities/:id' => 'oportunities#show', as: 'oportunity'
  get 'oportunities' => 'oportunities#index', as: 'oportunities'  
  get 'disciplines' => 'discipline#index', as: 'disciplines'
  
  namespace :dashboard do
    root 'articles#index', as: 'root'
    resources :articles, except: [:show]
    resources :events, except: [:show]
    resources :disciplines, except: [:show]
    resources :oportunities, except: [:show]
    resources :users, except: [:show]
    resources :discipline_classes, except: [:show]
    resources :materials, except: [:show]

    get 'profile' => 'profile#index', as: 'profile'
    post 'profile' => 'profile#update', as: 'profile_update'
  end

  scope 'portalC3' do
    namespace :api do
      get 'posts' => 'article#index'
      get 'posts/:id' => 'article#show'

      get 'eventos' => 'event#index'
      get 'eventos/:id' => 'event#show'

      get 'disciplinas' => 'discipline#index'

      get 'oportunidades' => 'oportunity#index'
      get 'oportunidades/:id' => 'oportunity#show'

      get 'professores' => 'teacher#index'
      get 'professores/:id' => 'teacher#show'
    end
  end

end

app/models/dashboard.rb
module Dashboard
  def self.table_name_prefix
    'dashboard_'
  end
end

app/models/discipline_class.rb
class DisciplineClass < ActiveRecord::Base
  belongs_to :user
  belongs_to :discipline
  has_many :class_files

  alias :attachments :class_files

  def attachments_array=(array)
    unless array.nil?
      array.each do |file|
        class_files.create(:attachment => file)
      end
    end
  end

  def make_json(request)
    files = []
    class_files.each do |file|
      files << file.json(request)
    end
    files
  end

end

app/models/user.rb
# Classe de usuário
class User < ActiveRecord::Base
  # Funcoes do devise
  # - database_authenticatable: Indica que essa classe é autenticável
  # - registerable: Indica que essa classe é registrável
  # - recoverable: Indica que essa classe possui recuperação de senha
  # - rememberable: Faz com que a autenticação se mantenha em cache
  # - trackable: Indica que essa classe é rastreável (Quantidade de logins, ultimo login, etc)
  # - validatable: Indica que essa classe é validável pelo devise (Tamanho da senha, campos obrigatórios, confirmação da senha)
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Enum de nível de usuário
  # são utilizados para saber que tipo de usuário
  # pode ou não criar e/ou remover outros usuários
  enum role: [:admin, :user]

  has_many :articles
  has_many :events
  has_many :events
  has_many :discipline_classes
  belongs_to :user_profile
  has_and_belongs_to_many :disciplines

  # Para facilitar o uso futuro, foi abreviado para profile apenas
  alias :profile :user_profile
  alias :classes :discipline_classes

  # Define o tipo de imagem que a notícia pode ter
  has_attached_file :avatar, :styles => {
      :medium => ["300x300>", :jpg],
      :thumb => ["100x100>", :jpg]
  }

  # Valida o tipo de arquivo a imagem da notícia pode ser
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.reset_password(id, password)
    user = find id
    user.password = password
    user.save
  end

end

app/controllers/dashboard/articles_controller.rb
class Dashboard::ArticlesController < Dashboard::AuthenticatedController
  before_action :set_dashboard_article, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin?
      @dashboard_articles = Article.order('articles.created_at desc').paginate(:page => params[:page], :per_page => 30).eager_load(:user)
    else
      @dashboard_articles = current_user.articles.order('articles.created_at desc').paginate(:page => params[:page], :per_page => 30).eager_load(:user)
    end
  end
  
  def new
    @dashboard_article = Article.new
  end

  def edit
    if @dashboard_article.user_id != current_user.id
      redirect_to dashboard_article_path
    end
  end

  def create
    @dashboard_article = Article.new(dashboard_article_params)
    @dashboard_article.user_id = current_user.id
    respond_to do |format|
      if @dashboard_article.save
        format.html { redirect_to dashboard_articles_url, notice: 'Notícias criada com sucesso.' }
        format.json { render :index, status: :created, location: @dashboard_article }
      else
        format.html { render :new }
        format.json { render json: @dashboard_article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @dashboard_article.update(dashboard_article_params)
        format.html { redirect_to dashboard_articles_url, notice: 'Notícia atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @dashboard_article }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dashboard_article.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_dashboard_article
      @dashboard_article = Article.find(params[:id])
    end

    def dashboard_article_params
      article = params.require(:article).permit(:title, :image, :description)
      if article[:image].nil?
        article.delete :image
      end
      article
    end
end

app/controllers/dashboard/authenticated_controller.rb
class Dashboard::AuthenticatedController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  layout 'dashboard'
  
  def is_admin?
    current_user.admin?
  end
  
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource)
  end

end

app/controllers/dashboard/discipline_classes_controller.rb
class Dashboard::DisciplineClassesController < Dashboard::AuthenticatedController
  before_action :set_class, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin?
      @classes = DisciplineClass.eager_load(:discipline).paginate(:page => params[:page], :per_page => 10)
    else
      @classes = current_user.classes.eager_load(:discipline).paginate(:page => params[:page], :per_page => 10)
    end
  end

  def new
    @class = DisciplineClass.new
  end

  def edit
  end

  def create
    args = class_param
    files = args[:attachment_array]
    args.delete :attachment_array
    @class = DisciplineClass.new(args)
    @class.user = current_user
    respond_to do |format|
      if @class.save
        @class.attachments_array = files
        format.html { redirect_to dashboard_discipline_classes_url }
        format.json { render :show, status: :created, location: @dashboard_discipline }
      else
        format.html { render :new }
        format.json { render json: @dashboard_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    args = class_param
    files = args[:attachment_array]
    args.delete :attachment_array
    respond_to do |format|
      if @class.update(args)
        @class.attachments_array = files
        ClassFile.destroy_all id: params[:destroy_files]
        format.html { redirect_to dashboard_discipline_classes_url }
        format.json { render :show, status: :ok, location: @dashboard_discipline }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/disciplines/1
  # DELETE /dashboard/disciplines/1.json
  def destroy
    @class.attachments.destroy
    @class.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_discipline_classes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_class
      @class = DisciplineClass
                   .eager_load(:class_files)
                   .find(params[:id])
    end

  def class_param
    params.require(:discipline_class).permit!
  end

  def file_param
    params.require(:file).permit!
  end
end

app/controllers/dashboard/disciplines_controller.rb
class Dashboard::DisciplinesController < Dashboard::AuthenticatedController
  before_action :set_dashboard_discipline, only: [:show, :edit, :update, :destroy]

  # GET /dashboard/disciplines
  # GET /dashboard/disciplines.json
  def index
    if current_user.admin?
      @dashboard_disciplines = Discipline.paginate(:page => params[:page], :per_page => 10)
    else
      @dashboard_disciplines = current_user.disciplines.paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /dashboard/disciplines/1
  # GET /dashboard/disciplines/1.json
  def show
  end

  # GET /dashboard/disciplines/new
  def new
    @dashboard_discipline = Discipline.new
  end

  # GET /dashboard/disciplines/1/edit
  def edit
  end

  # POST /dashboard/disciplines
  # POST /dashboard/disciplines.json
  def create
    @dashboard_discipline = Discipline.new(dashboard_discipline_params)

    respond_to do |format|
      if @dashboard_discipline.save
        format.html { redirect_to dashboard_disciplines_path, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard_discipline }
      else
        format.html { render :new }
        format.json { render json: @dashboard_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/disciplines/1
  # PATCH/PUT /dashboard/disciplines/1.json
  def update
    respond_to do |format|
      if @dashboard_discipline.update(dashboard_discipline_params)
        format.html { redirect_to dashboard_disciplines_path, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard_discipline }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/disciplines/1
  # DELETE /dashboard/disciplines/1.json
  def destroy
    DisciplineClass.destroy_all(:discipline_id => @dashboard_discipline.id)
    @dashboard_discipline.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_disciplines_path, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_discipline
      @dashboard_discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_discipline_params
      params.require(:discipline).permit(:name, :link, :code, :credit, :hours, :semester, :shift, :image, user_ids: [])
    end
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < Dashboard::AuthenticatedController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.order('created_at desc').paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    respond_to do |format|
      if @event.save
        format.html { redirect_to dashboard_events_url, notice: 'Evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to dashboard_events_url, notice: 'Evento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_events_url, notice: 'Evento removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  def set_event
    @event = Event.find_by_id params[:id]
  end

  def event_params
    params.require(:event).permit(:title, :description, :id, :place, :date, :image)
  end
end

app/controllers/dashboard/materials_controller.rb
class Dashboard::MaterialsController < Dashboard::AuthenticatedController
  before_action :set_dashboard_material, only: [:show, :edit, :update, :destroy]
  # GET /dashboard/materials
  # GET /dashboard/materials.json
  def index
    if current_user.admin?
      @dashboard_materials = Material.paginate(:page => params[:page], :per_page => 10)
    else
      @dashboard_materials = current_user.materials.paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /dashboard/disciplines/1/edit
  def edit
  end   
   # POST /dashboard/materials
  # POST /dashboard/materials.json
  def create

    @dashboard_material = Material.new(dashboard_material_params)

    respond_to do |format|
      if @dashboard_material.save
        format.html { redirect_to dashboard_materials_path, notice: 'material was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard_material }
      else
        format.html { render :new }
        format.json { render json: @dashboard_material.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /dashboard/disciplines/new
  def new
    @dashboard_material = Material.new
  end

  # PATCH/PUT /dashboard/materials/1
  # PATCH/PUT /dashboard/materials/1.json
  def update
    respond_to do |format|
      if @dashboard_material.update(dashboard_material_params)
        format.html { redirect_to dashboard_materials_path, notice: 'material was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard_material }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/materials/1
  # DELETE /dashboard/materials/1.json
  def destroy
    MaterialClass.destroy_all(:material_id => @dashboard_material.id)
    @dashboard_material.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_materials_path, notice: 'material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   
   private
      # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_material
      @dashboard_material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_material_params
      params.require(:material).permit(:name, :attachment, :discipline_id)
   end
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < Dashboard::AuthenticatedController

  def index

  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        current_user.profile.update(profile_params)
        sign_in(current_user, :bypass => true)
        flash['alert alert-success'] = 'Usuário atualizado com sucesso.'
        format.html { redirect_to dashboard_root_path }
        format.json { render :index, status: :ok, location: current_user }
      else
        format.html { render :index }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def user_params
    user = params.require(:user).permit!
    if user[:password].nil? or user[:password].empty?
      user.delete :password
      user.delete :password_confirmation
    end
    user
  end

  def profile_params
    params.require(:user_profile).permit!
  end
end

app/helpers/dashboard/articles_helper.rb
module Dashboard::ArticlesHelper
end

app/helpers/dashboard/disciplines_helper.rb
module Dashboard::DisciplinesHelper
end

app/helpers/dashboard/events_helper.rb
module Dashboard::EventsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/views/dashboard/discipline_classes/_form.html.erb
<div class="botao2">
  <% if not @class.new_record? %>
      <%= link_to 'Remover', {:controller => :discipline_classes  ,
                              :action => 'destroy', :id => @class.id },:class => "btn btn-danger", :method => :delete %>
  <% end %>
  <a href="<%= dashboard_discipline_classes_path %>"><button class="btn btn-primary">Voltar</button></a>
</div>
<%= form_for([:dashboard, @class], :multipart => true) do |f| %>
    <section class="content">
      <section class="widget" style="min-height:00px">
        <header>
          <% if @class.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@class.errors.count, "error") %>:</h2>

                <ul>
                  <% @class.errors.full_messages.each do |message| %>
                      <li>
                        <%= message %>
                      </li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          <span class="icon">&#59160;</span>
          <hgroup>
            <h1>Turmas</h1>
            <h2><%= @class.new_record? ? 'Inserir uma nova turma' : 'Modificar turma' %></h2>
          </hgroup>
        </header>
        <div class="content">
          <div class="field-wrap">
            <label>Nome:</label>
            <%= f.text_field :name, placeholder: 'Nome' %>
          </div>

          <div class="field-wrap">
            <lavel>Disciplina:</lavel>
            <%= f.select :discipline_id, current_user.disciplines.collect {|a| ["#{a.name} - #{a.night? ? 'Noite' : 'Tarde'}", a.id]} %>
          </div>

          <div class="field-wrap">
            <lavel>Arquivos:</lavel>
            <%= f.file_field :attachment_array, multiple:true %>
          </div>
          <% if @class.class_file_ids.size > 0 %>
              <div class="file-wrap">
                <label>Remover arquivos:</label>
                <% @class.class_files.each do |attachment| %>
                    <div class="file-wrap">
                      <label><input name="destroy_files[]" type="checkbox" style="width: 1%;" value="<%= attachment.id %>"/> <%= attachment.original_filename %></label>
                    </div>
                <% end %>
              </div>
          <% end %>

          <br>
          <br>
          <% if current_user.discipline_ids.length > 0 %>
            <div id="botoess">
              <%= f.button 'Salvar', class: 'green', type: 'submit' %>
            </div>
          <% else %>
            <div id="botoess">
              <label>Você precisa possuir mais de uma disciplina para continuar </label>  
            </div>
          <% end %>
        </div>
      </section>
    </section>
<% end %>

app/views/dashboard/discipline_classes/index.html.erb
<section class="content">
  <section class="widget">
    <header>
      <span class="icon">&#59160;</span>
      <hgroup>
        <h1>Turmas</h1>
        <h2>Turmas cadastradas</h2>
      </hgroup>

    </header>
    <div class="content">
      <div class="gutter">
        <div class="col-lg-12">
          <div class="portal_pagination">
            <%= will_paginate @classes, :previous_label => 'Anterior', :next_label => 'Próximo'%>
          </div>
        </div>
      </div>
      <table id="myTable" border="0" width="100">
        <thead>
        <tr>
          <th>Nome</th>
          <th>Disciplina</th>
          <th>Criação</th>
          <% if current_user.admin? %>
              <th>Professor</th>
          <% end %>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @classes.each do |klass| %>
            <tr>
              <td>
                <%= link_to klass.name,  edit_dashboard_discipline_class_path(klass) %>
              </td>
              <td>
                <%= link_to "#{klass.discipline.name} - #{klass.discipline.night? ? 'Noite' : 'Tarde'}",  edit_dashboard_discipline_path(klass.discipline) %>
              </td>
              <td>
                <%= link_to klass.created_at,  edit_dashboard_discipline_class_path(klass) %>
              </td>
              <% if current_user.admin? %>
                  <td>
                    <%= link_to klass.user_id == current_user.id ? 'Você' : klass.user.name,  edit_dashboard_discipline_class_path(klass) %>
                  </td>
              <% end %>
              <td>
                <%= link_to 'Remover', {:controller => :discipline_classes,
                                        :action => 'destroy', :id => klass.id },:class => "btn btn-danger", :method => :delete %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </section>
</section>