config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  devise_for :users, skip: :registrations, controllers: {
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
  }

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root 'welcome#index', as: 'home'
  
  get 'about' => 'welcome#about', as: 'about'
  get '404' => 'welcome#not_found', as: 'not_found'
  
  get 'articles' => 'articles#index', as: 'articles'
  get 'articles/:id' => 'articles#show', as: 'article'

  get 'events/:id' => 'events#show', as: 'event'
  get 'events' => 'events#index', as: 'events'

  get 'teachers/:id' => 'teacher#show', as: 'teacher'
  get 'teachers' => 'teacher#index', as: 'teachers'
  
  get 'oportunities/:id' => 'oportunities#show', as: 'oportunity'
  get 'oportunities' => 'oportunities#index', as: 'oportunities'  
  get 'disciplines' => 'discipline#index', as: 'disciplines'
  
  namespace :dashboard do
    root 'articles#index', as: 'root'
    resources :articles, except: [:show]
    resources :events, except: [:show]
    resources :disciplines, except: [:show]
    resources :oportunities, except: [:show]
    resources :users, except: [:show]
    resources :discipline_classes, except: [:show]
    resources :materials, except: [:show]

    get 'profile' => 'profile#index', as: 'profile'
    post 'profile' => 'profile#update', as: 'profile_update'
  end

  scope 'portalC3' do
    namespace :api do
      get 'posts' => 'article#index'
      get 'posts/:id' => 'article#show'

      get 'eventos' => 'event#index'
      get 'eventos/:id' => 'event#show'

      get 'disciplinas' => 'discipline#index'

      get 'oportunidades' => 'oportunity#index'
      get 'oportunidades/:id' => 'oportunity#show'

      get 'professores' => 'teacher#index'
      get 'professores/:id' => 'teacher#show'
    end
  end

end

app/models/oportunity.rb
class Oportunity < ActiveRecord::Base
    belongs_to :user
    
        # Define o tipo de imagem que a notícia pode ter
    has_attached_file :image, :styles => { 
        :medium => ["300x300>", :jpg], 
        :thumb => ["100x100>", :jpg] 
    }

    # Valida o tipo de arquivo a imagem da notícia pode ser
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    
end

app/controllers/api/oportunity_controller.rb
class Api::OportunityController < ApplicationController

    def index
        @oportunities = Oportunity.paginate(:page => params[:page], :per_page => 30)
        @json_oportunities = []
        for oportunity in @oportunities
            @post = to_json oportunity
            @json_oportunities << @post
        end
        render :json => @json_oportunities
    end
    
    def show
        @oportunity = Oportunity.find params[:id]
        
        render :json => to_json(@oportunity)
    end
    
    private
    def to_json(oportunity)
        oportunity.to_json
        {
            oportunidadeId: oportunity.id,
            oportunidadeTitulo: oportunity.title,
            oportunidadeDescricao: ActionController::Base.helpers.strip_tags(oportunity.description),
            oportunidadeData: oportunity.created_at,
            oportunidadeEmpresa: oportunity.employer,
            oportunidadeImagemUrl: "#{request.protocol}#{request.host}#{oportunity.image.url}"
        }
    end

end

app/controllers/dashboard/oportunities_controller.rb
class Dashboard::OportunitiesController < Dashboard::AuthenticatedController
  before_action :set_oportunity, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin?
      @oportunities = Oportunity.order('created_at desc').paginate(:page => params[:page], :per_page => 10)
    else
      @oportunities = Oportunity.where(user_id: current_user.id).order('created_at desc').paginate(:page => params[:page], :per_page => 10)
    end
  end


  def show
  end

  def new
    @oportunity = Oportunity.new
  end

  def edit
  end

  def create
    @oportunity = Oportunity.new(oportunity_params)
    @oportunity.user = current_user

    respond_to do |format|
      if @oportunity.save
        format.html { redirect_to @oportunity, notice: 'Oportunidade criada com sucesso.' }
        format.json { render :show, status: :created, location: @oportunity }
      else
        format.html { render :new }
        format.json { render json: @oportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @oportunity.update(oportunity_params)
        format.html { redirect_to @oportunity, notice: 'Oportunidade atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @oportunity }
      else
        format.html { render :edit }
        format.json { render json: @oportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @oportunity.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_oportunities_url, notice: 'Oportunidade removida!' }
      format.json { head :no_content }
    end
  end

  private
    def set_oportunity
      @oportunity = Oportunity.find(params[:id])
    end

    def oportunity_params
      params.require(:oportunity).permit!
    end
end

app/controllers/oportunities_controller.rb
class OportunitiesController < ApplicationController
  def index
    @oportunities = Oportunity.order('created_at desc').paginate(:page => params[:page], :per_page => 30)
  end

  def show
    begin
      @oportunity = Oportunity.find params[:id]
    rescue
      redirect_to not_found_path()
    end
  end
end

app/helpers/oportunity_helper.rb
module OportunityHelper
end

app/views/oportunities/index.html.erb
<div class="col-lg-8 col-md-8">
    <div class="col-padded">
        <div class="gutter">
            <div class="col-lg-12 col-md-12">
                <h1 class="page-title">Oportunidades</h1>
            </div>
        </div>
        <div class="gutter">
            <div class="col-lg-12 col-md-12">
                <% @oportunities.each do |oportunity| %>
                <div class="news-mini-wrap col-lg-6 col-md-6">
                    <figure class="news-featured-image">
                        <a href="<%= oportunity_path(oportunity) %>" title="<%= oportunity.title%>">
                            <%= image_tag oportunity.image.url(:thumb), class: 'attachment-thumbnail wp-post-image' %>
                        </a>
                    </figure>
                    <div class="page-title-meta">
                        <h1 class="title-median"><%= link_to oportunity.title, oportunity_path(oportunity)%></h1>
                        <span class="news-meta-date"><b>Publicado em:</b> <%= oportunity.created_at.strftime("%d/%m/%Y")%></span>
                        <p><span class="news-meta-date"><b>Empresa:</b> <%= oportunity.employer%></span></p>
                        <div class="news-summary">
                            <p>
                                <%= sanitize oportunity.description[0..30]%>...
                            </p>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
        <div class="gutter">
            <div class="col-lg-12">
                <%= will_paginate @oportunities, :previous_label => 'Anterior', :next_label => 'Próximo' %>
            </div>
        </div>
    </div>
</div>

app/views/oportunities/show.html.erb
<div class="col-lg-8 col-md-8">
    <div class="col-padded">
        <div class="row gutter">
            <div class="col-lg-12 col-md-12">
                <h1 class="page-title"><%= @oportunity.title %></h1>
                <span class="news-meta-date"><b>Publicação:</b> <%= @oportunity.created_at.strftime("%d/%m/%Y")%><p><b>Empresa:</b> <%= @oportunity.employer %></p></span>
                <figure class="news-featured-image">
                    <br><img src="<%= @oportunity.image.url %>" alt="<%= @oportunity.title %>" class="img-responsive">
                </figure>
                <div class="news-body">
                    <p class="call-out">
                        <p align="justify">
                            <%= @oportunity.description.html_safe %>
                        </p>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>